# fly.toml app configuration file generated for runscrapp on 2023-06-07T11:10:22+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "runscrapp"
primary_region = "cdg"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
