spring:
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
  datasource:

    url: jdbc:postgresql://lucky.db.elephantsql.com:5432/roblqurx
    driver-class-name: org.postgresql.Driver
    username: roblqurx
    password: exHzDY29zXoM-dTbfsabErskZSaDRXZb
    hikari:
      autoCommit: true
      idleTimeout: 1000
      minimumIdle: 5
      maximumPoolSize: 2
      maxLifetime: 30000
      poolName: HikariQuizz

  shell:
    interactive:
      enabled: false



server:
  port: 8080

maxmind:
  userid: 875725
  password: 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
